// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpwcmlepgdmkhcjxzbzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwd2NtbGVwZ2Rta2hjanh6YnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3ODg3OTIsImV4cCI6MjA1MTM2NDc5Mn0.91h52VpZ8HVEuYRZ-hwWg_6gatLj6Yo2g-zgq44hLso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);